USE [Renn_App_DB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE MAILING_LIST(
	[MAILING_LIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](30) NOT NULL,
	[LAST_NAME] [varchar](30) NOT NULL,
	[EMAIL_ADDRESS] [varchar](50) NOT NULL,
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_MAILING_LIST] PRIMARY KEY NONCLUSTERED 
(
	[MAILING_LIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE AUDIT(
	[AUDIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[AUDIT_TYPE] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](500) NULL,	
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_AUDIT] PRIMARY KEY NONCLUSTERED 
(
	[AUDIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE MEDIA(
	[MEDIA_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEDIA_NAME] [varchar](50) NOT NULL,
	[MEDIA_SIZE] [varchar](500) NULL,	
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_MEDIA] PRIMARY KEY NONCLUSTERED 
(
	[MEDIA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE APP_USER(
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](25) NOT NULL,
	[FIRST_NAME] [varchar](30) NOT NULL,
	[LAST_NAME] [varchar](30) NOT NULL,	
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_APP_USER] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE ANNOUNCEMENT(
	[ANNOUNCEMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ANNOUNCEMENT_TYP] [varchar](50) NOT NULL,
	[ANNOUNCEMENT_MSG] [varchar](500) NULL,	
	[USER_ID] [int] NULL,	
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_ANNOUNCEMENT] PRIMARY KEY CLUSTERED 
(
	[ANNOUNCEMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_ANNOUNCEMENT] UNIQUE NONCLUSTERED 
(
	[USER_ID] ASC
	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE TABLE APPOINTMENT(
	[APPOINTMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[ATTENDEE_FIRST_NAME] [varchar](30) NOT NULL,
	[ATTENDEE_LAST_NAME] [varchar](30) NULL,
	[ATTENDEE_EMAIL] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](128) NULL,	
	[APPOINTMENT_DATE] DATE NULL,	
	[START_TIME] DATETIME NULL,	
	[END_TIME] DATETIME NULL,	
	[USER_ID] [int] FOREIGN KEY REFERENCES [APP_USER](USER_ID) NULL,	
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_APPOINTMENT] PRIMARY KEY CLUSTERED 
(
	[APPOINTMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE TABLE USER_LOGIN(
	[LOGIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] FOREIGN KEY REFERENCES [APP_USER](USER_ID) NULL,
	[SALT] [binary](32) NOT NULL,
	[CREDENTIALS_HASH] [binary](32) NOT NULL,
	[ITERATIONS] [int] NOT NULL,		
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_USER_LOGIN] PRIMARY KEY CLUSTERED 
(
	[LOGIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UNQ_USER_LOGIN] UNIQUE NONCLUSTERED 
(
	[USER_ID] ASC
	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

CREATE TABLE AVAILABILITY_SCHEDULE(
	[SCHEDULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] FOREIGN KEY REFERENCES [APP_USER](USER_ID) NULL,
	[AVAILABLE] [int] NOT NULL,
	[START_TIME] DATETIME NOT NULL,
	[END_TIME] DATETIME NOT NULL,
	[RECURRENCE] [int] NULL,
	[UPDATED_BY] [varchar](128) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_AVAILABILITY_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[SCHEDULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_AVAILABILITY_SCHEDULE] UNIQUE NONCLUSTERED 
(
	[USER_ID] ASC
	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO